require("test.dns_lookup_test")
require("test.tcp_client_test")
require("test.tcp_client_server")
require("test.udp_client_server")

require("examples.dns_lookup")
require("examples.tcp_client_blocking")
require("examples.tcp_client_nonblocking")
require("examples.tcp_client_blocking_tls")
require("examples.tcp_client_nonblocking_tls")