name: build
on: [push]

jobs:
  ljsocket-linux:
    runs-on: ubuntu-latest
    container:
      image: debian:latest

    steps:
      - name: checkout the project
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          apt-get update
          apt-get install -y build-essential git

      - name: Build and install LuaJIT from source
        run: |
          cd /tmp
          git clone https://luajit.org/git/luajit.git
          cd luajit
          make
          make install
          
          LUAJIT_BIN=$(find /usr/local/bin -name 'luajit-*' -type f | head -n 1)
          if [ -n "$LUAJIT_BIN" ]; then
            ln -sf "$LUAJIT_BIN" /usr/local/bin/luajit
          fi
          
          ldconfig
          
      - name: Verify LuaJIT installation
        run: |
          which luajit
          luajit -v
      
      - name: Run tests
        run: |
          luajit test/run.lua

  ljsocket-windows:
    runs-on: windows-latest

    steps:
      - name: checkout the project
        uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            make
            mingw-w64-x86_64-gcc

      - name: Build and install LuaJIT from source
        shell: msys2 {0}
        run: |
          cd /tmp
          git clone https://luajit.org/git/luajit.git
          cd luajit
          make BUILDMODE=static
          make install PREFIX=/mingw64

      - name: Verify LuaJIT installation
        shell: msys2 {0}
        run: |
          luajit -v
      
      - name: Run tests
        shell: msys2 {0}
        run: |
          cd "$GITHUB_WORKSPACE"
          luajit test/run.lua