name: build
on: [push]

jobs:
  ljsocket:
    runs-on: ubuntu-latest
    container:
      image: debian:latest

    steps:
      - name: checkout the project
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          apt-get update
          apt-get install -y build-essential git

      - name: Build and install LuaJIT from source
        run: |
          cd /tmp
          git clone https://luajit.org/git/luajit.git
          cd luajit
          make
          make install
          
          # Create symlink from versioned binary to 'luajit'
          LUAJIT_BIN=$(find /usr/local/bin -name 'luajit-*' -type f | head -n 1)
          if [ -n "$LUAJIT_BIN" ]; then
            ln -sf "$LUAJIT_BIN" /usr/local/bin/luajit
          fi
          
          ldconfig
          
      - name: Verify LuaJIT installation
        run: |
          which luajit
          luajit -v
      
      - name: Run tests
        run: |
          luajit test/run.lua